<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Veinmine</AssemblyName>
    <RootNamespace>Veinmine</RootNamespace>
    <Version>0.2.2</Version>
    <Deterministic>true</Deterministic>
    <ThunderstorePackageName>StrVeinMine</ThunderstorePackageName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies"
                      Version="1.0.3"
                      PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild"
                      Version="0.5.0-beta.2"
                      PrivateAssets="all" />
    <PackageReference Include="ILRepack.Lib.MSBuild.Task"
                      Version="2.0.46"
                      PrivateAssets="all" />
  </ItemGroup>

</Project>
