<Project>
  <PropertyGroup>
    <ValheimManagedPath Condition="'$(ValheimManagedPath)' == ''">$(VALHEIM_MANAGED_PATH)</ValheimManagedPath>
    <BepInExPath Condition="'$(BepInExPath)' == ''">$(BEPINEX_PATH)</BepInExPath>
    <ReleaseOutputPath Condition="'$(ReleaseOutputPath)' == ''">$(MSBuildThisFileDirectory)release</ReleaseOutputPath>
    <ServerSyncPath Condition="'$(ServerSyncPath)' == ''">$(BepInExPath)/core/ServerSync.dll</ServerSyncPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="assembly_valheim">
      <HintPath>$(ValheimManagedPath)/assembly_valheim.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(ValheimManagedPath)/assembly_utils.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>$(ValheimManagedPath)/assembly_guiutils.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="ServerSync">
      <HintPath>$(ServerSyncPath)</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExPath)/core/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExPath)/core/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ValheimManagedPath)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ValheimManagedPath)/UnityEngine.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ValheimManagedPath)/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ValheimManagedPath)/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
  </ItemGroup>
</Project>
